version: '3'
services:
  react:
    container_name: react-container
    build: ./client
    image: react-image
    restart: always
    ports:
      - "3000:3000"
    environment:
      EXPRESS_URL: "http://localhost:3001"
    depends_on:
      - express
  express:
    container_name: express-container
    build: ./express-app
    image: express-image
    restart: always
    ports:
      - "3001:3001"
  nginx:
    container_name: nginx-container
    build: ./nginx
    image: nginx-image
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - react
      - express
